In [3]:
import numpy as np 

## Creating array from Python list  
---

In [11]:
my_arr = np.array([2, 4, 5, 6])
print(my_arr)
print(type(my_arr))

[2 4 5 6]
<class 'numpy.ndarray'>


In [15]:
# Float data Type 
np.array([1, 2.4, 2, 4]) # Converts all items to float

array([1. , 2.4, 2. , 4. ])

In [14]:
# int and string in list
np.array([1, 3.0, 5, "str"]) # Converts all items to Str

array(['1', '3.0', '5', 'str'], dtype='<U32')

`We can also explicitly set the data type of the array using hte dtype keyword, as follow:`

In [16]:
np.array([1.24, 2, 3, 4], dtype='int16') # 16 represents no of bit

array([1, 2, 3, 4], dtype=int16)

In [17]:
np.array([1.25, 2, 3, 4], dtype='float32')

array([1.25, 2.  , 3.  , 4.  ], dtype=float32)

## Multi dimensional array 
---

In [19]:
np.array([  [1, 2, 3], 
            [4, 5, 6], 
            [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [24]:
np.ones((5, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Some numpy methods
---

In [28]:
np.arange(1, 31, 1) # starting: stoping: step

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
np.linspace(0, 1, 5) # linspace = linear spacing # eqully spaces and it's inclusive

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Numpy random

In [34]:
np.random.random((3, 3))

array([[0.02310022, 0.59254043, 0.37369436],
       [0.28698824, 0.24968674, 0.66606117],
       [0.8233144 , 0.63133645, 0.80869642]])

In [51]:
# Create a 3x3 array of normally distributed random values with mean (avarage) 
# 0 mean and standard deviation 1 
np.random.normal(0, 1, (3, 3)) # first parameter = mean; second = standard deviation; third = dimension 

array([[-1.20574758,  1.08626708, -1.780056  ],
       [-0.08679959,  0.44222258,  0.89270387],
       [-1.10544765,  1.35215636,  1.17044169]])

In [44]:
# discriptive stat => mean median  and infrencial stat => result and conclusion; hypothesis testing, normalization

In [48]:
np.random.randint(0, 10, (3, 2)) #first parameter: start; second: stop; third: dimension

array([[4, 7],
       [9, 6],
       [1, 0]])

### Identity metrix 

In [53]:
# Identity metrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Empty array 

In [50]:
# creates array without initializating it 
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])